name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install ldid ripgrep dpkg make
          git clone --recursive https://github.com/roothide/theos.git $HOME/theos
          
      - name: Build Packages
        run: |
          export THEOS=$HOME/theos
          export BUILD_NUMBER=${{ github.run_number }}
          make package-all
          for f in packages/*.deb; do mv "$f" "${f/-arm64.deb/-arm64e.deb}"; done

      - name: Get Version
        id: get_version
        run: |
          BASE_VERSION=$(grep "BASE_VERSION ?=" Config.mk | awk '{print $3}')
          echo "version=${BASE_VERSION}-b${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: MarkTheme64e v${{ steps.get_version.outputs.version }}
          files: packages/*.deb
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
